#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

		[types.stone_type.atmospheric]
			ivory_travertine = true
			peach_travertine = true
			persimmon_travertine = true
			saffron_travertine = true
			dolerite = true

		[types.stone_type.arts_and_crafts]
			white_chalk = true
			gypsum = true
			soapstone = true

		[types.stone_type.create]
			limestone = true
			asurine = true
			crimsite = true
			ochrum = true
			veridium = true
			scoria = true
			scorchia = true

		[types.stone_type.deep_aether]
			clorite = true
			raw_clorite = true
			aseterite = true

		[types.stone_type.regions_unexplored]
			argillite = true
			chalk = true

		[types.stone_type.northstar]
			mars_stone = true
			moon_stone = true
			venus_stone = true
			mercury_stone = true

		[types.stone_type.garnished]
			carnotite = true
			abyssal_stone = true
			ritualistic_stone = true
			unstable_stone = true
			dragon_stone = true
			zultanite = true

		[types.stone_type.aether]
			holystone = true

		[types.stone_type.dndecor]
			cut_stone = true

		[types.stone_type.enderscape]
			mirestone = true
			veradite = true
			kurodite = true

		[types.mud_type.deep_aether]
			aether_mud = true

		[types.cake.createfood]
			cream_cake_chorus_fruit = true
			cream_cake_glow_berry = true
			berry_cream_cake_sweet_berry = true
			berry_cream_cake_chorus_fruit = true
			berry_cream_cake_glow_berry = true
			chocolate_cream_cake_butterscotch = true
			chocolate_cream_cake_caramel = true
			chocolate_cream_cake_chocolate = true
			chocolate_cream_cake_dark_chocolate = true
			chocolate_cream_cake_toffee = true
			chocolate_cream_cake_white_chocolate = true
			chorus_fruit_cream_cake_sweet_berry = true
			chorus_fruit_cream_cake_chorus_fruit = true
			chorus_fruit_cream_cake_glow_berry = true
			glow_berry_cream_cake_sweet_berry = true
			glow_berry_cream_cake_chorus_fruit = true
			glow_berry_cream_cake_glow_berry = true

		[types.wood_type.createdieselgenerators]
			chip_wood = true

		[types.wood_type.cobblemon]
			apricorn = true

		[types.wood_type.northstar]
			wilter = true
			argyre = true
			coiler = true
			calorian = true

		[types.wood_type.garnished]
			sepia = true
			nut = true

		[types.wood_type.aether]
			skyroot = true

		[types.wood_type.deep_aether]
			roseroot = true
			yagroot = true
			cruderoot = true
			conberry = true
			sunroot = true

		[types.wood_type.arts_and_crafts]
			cork = true

		[types.wood_type.upgrade_aquatic]
			driftwood = true
			river = true

		[types.wood_type.autumnity]
			maple = true

		[types.wood_type.regions_unexplored]
			alpha = true
			baobab = true
			blackwood = true
			blue_bioshroom = true
			brimwood = true
			cobalt = true
			cypress = true
			dead = true
			eucalyptus = true
			green_bioshroom = true
			joshua = true
			kapok = true
			larch = true
			magnolia = true
			maple = true
			mauve = true
			palm = true
			pine = true
			pink_bioshroom = true
			redwood = true
			socotra = true
			willow = true
			yellow_bioshroom = true

		[types.wood_type.enderscape]
			veiled = true
			celestial = true
			murublight = true

		[types.wood_type.atmospheric]
			rosewood = true
			morado = true
			yucca = true
			aspen = true
			laurel = true
			kousa = true
			grimwood = true

		[types.leaves_type.cobblemon]
			apricorn = true

		[types.leaves_type.northstar]
			wilter = true
			argyre = true
			coiler = true

		[types.leaves_type.aether]
			skyroot = true
			golden_oak = true
			crystal = true
			crystal_fruit = true
			holiday = true
			decorated_holiday = true

		[types.leaves_type.deep_aether]
			roseroot = true
			flowering_roseroot = true
			blue_roseroot = true
			flowering_blue_roseroot = true
			yagroot = true
			cruderoot = true
			conberry = true
			sunroot = true

		[types.leaves_type.arts_and_crafts]
			cork = true

		[types.leaves_type.culturaldelights]
			avocado = true
			fruiting_avocado = true

		[types.leaves_type.alolan_adventures]
			palm = true

		[types.leaves_type.upgrade_aquatic]
			river = true

		[types.leaves_type.autumnity]
			maple = true
			yellow_maple = true
			orange_maple = true
			red_maple = true

		[types.leaves_type.regions_unexplored]
			alpha = true
			apple_oak = true
			bamboo = true
			baobab = true
			blackwood = true
			magnolia = true
			cypress = true
			dead = true
			dead_pine = true
			eucalyptus = true
			flowering = true
			golden_larch = true
			kapok = true
			larch = true
			maple = true
			mauve = true
			orange_maple = true
			palm = true
			pine = true
			blue_magnolia = true
			pink_magnolia = true
			redwood = true
			red_maple = true
			brimwood = true
			enchanted_birch = true
			small_oak = true
			silver_birch = true
			socotra = true
			white_magnolia = true
			willow = true
			ashen = true

		[types.leaves_type.atmospheric]
			rosewood = true
			morado = true
			flowering_morado = true
			yucca = true
			aspen = true
			green_aspen = true
			laurel = true
			dry_laurel = true
			kousa = true
			currant = true
			grimwood = true

#Disables specific entries
[entries]

		[entries.stone_type.additional_lights]
			standing_torch_l_polished = true
			standing_torch_s_smooth = true
			fire_pit_s_mossy_bricks = true
			fire_pit_l_bricks = true
			al_lamp = true
			fire_pit_s_bricks = true
			standing_torch_l_mossy_bricks = true
			standing_torch_l_smooth = true
			fire_pit_l_polished = true
			fire_pit_s = true
			standing_torch_l_bricks = true
			fire_pit_l = true
			standing_torch_s_mossy_bricks = true
			fire_pit_s_smooth = true
			standing_torch_l = true
			fire_pit_l_smooth = true
			standing_torch_s = true
			standing_torch_s_bricks = true
			fire_pit_s_polished = true
			fire_pit_l_mossy_bricks = true
			standing_torch_s_polished = true

		[entries.stone_type.mcwpaths]
			running_bond = true
			mossy_running_bond = true
			windmill_weave_slab = true
			mossy_strewn_rocky_path = true
			mossy_running_bond_path = true
			running_bond_path = true
			crystal_floor_path = true
			strewn_rocky_path = true
			mossy_flagstone_slab = true
			running_bond_slab = true
			mossy_flagstone_path = true
			mossy_running_bond_slab = true
			flagstone = true
			crystal_floor_slab = true
			mossy_crystal_floor = true
			mossy_windmill_weave_slab = true
			mossy_windmill_weave_path = true
			mossy_windmill_weave = true
			mossy_crystal_floor_path = true
			flagstone_slab = true
			crystal_floor = true
			mossy_flagstone = true
			mossy_crystal_floor_slab = true
			flagstone_path = true
			windmill_weave = true
			windmill_weave_path = true

		[entries.stone_type.handcrafted]
			corner_trim = true
			pillar_trim = true

		[entries.stone_type.mcwroofs]
			top_roof = true
			lower_roof = true
			upper_steep_roof = true
			steep_roof = true
			bricks_steep_roof = true
			bricks_roof = true
			upper_lower_roof = true
			bricks_top_roof = true
			attic_roof = true
			bricks_attic_roof = true
			roof = true
			bricks_lower_roof = true
			bricks_upper_steep_roof = true
			bricks_upper_lower_roof = true

		[entries.stone_type.create]
			cut_wall = true
			cut_brick_slab = true
			polished_cut_slab = true
			small_brick_wall = true
			cut = true
			cut_stairs = true
			small_brick_stairs = true
			cut_bricks = true
			small_bricks = true
			layered = true
			cut_brick_wall = true
			pillar = true
			cut_brick_stairs = true
			polished_cut_wall = true
			cut_slab = true
			polished_cut = true
			small_brick_slab = true
			polished_cut_stairs = true

		[entries.stone_type.mcwbridges]
			mossy_bridge_pier = true
			bridge_pier = true
			mossy_bridge_stair = true
			balustrade_mossy_bricks_bridge = true
			bridge = true
			balustrade_bricks_bridge = true
			mossy_brick_bridge = true
			brick_bridge_stair = true
			brick_bridge = true

		[entries.stone_type.mcwfences]
			modern_brick_wall = true
			railing_gate = true
			grass_topped_wall = true
			railing_wall = true
			railing_brick_wall = true
			pillar_wall = true
			modern_wall = true
			brick_railing_gate = true

		[entries.stone_type.mcwwindows]
			window2 = true
			brick_gothic = true
			pane_window = true
			brick_arrow_slit = true
			four_window = true
			window = true

		[entries.wood_type.handcrafted]
			counter = true
			corner_trim = true
			fancy_bed = true
			desk = true
			dining_bench = true
			drawer = true
			side_table = true
			couch = true
			table = true
			chair = true
			shelf = true
			cupboard = true
			bench = true
			pillar_trim = true
			nightstand = true

		[entries.wood_type.mcwroofs]
			planks_upper_steep_roof = true
			top_roof = true
			lower_roof = true
			planks_roof = true
			upper_steep_roof = true
			steep_roof = true
			upper_lower_roof = true
			attic_roof = true
			planks_upper_lower_roof = true
			roof = true
			planks_attic_roof = true
			planks_top_roof = true
			planks_steep_roof = true
			planks_lower_roof = true

		[entries.wood_type.mcwtrpdoors]
			ranch_trapdoor = true
			beach_trapdoor = true
			swamp_trapdoor = true
			glass_trapdoor = true
			whispering_trapdoor = true
			blossom_trapdoor = true
			tropical_trapdoor = true
			cottage_trapdoor = true
			paper_trapdoor = true
			bark_trapdoor = true
			classic_trapdoor = true
			bamboo_trapdoor = true
			barn_trapdoor = true
			four_panel_trapdoor = true
			barred_trapdoor = true
			mystic_trapdoor = true
			barrel_trapdoor = true

		[entries.wood_type.mcwwindows]
			louvered_shutter = true
			plank_pane_window = true
			plank_four_window = true
			stripped_log_window2 = true
			log_parapet = true
			window2 = true
			stripped_log_four_window = true
			stripped_log_window = true
			plank_window = true
			plank_window2 = true
			pane_window = true
			stripped_pane_window = true
			four_window = true
			plank_parapet = true
			blinds = true
			window = true
			shutter = true

		[entries.wood_type.mcwdoors]
			japanese2_door = true
			tropical_door = true
			barn_glass_door = true
			four_panel_door = true
			beach_door = true
			waffle_door = true
			japanese_door = true
			stable_door = true
			modern_door = true
			nether_door = true
			stable_head_door = true
			cottage_door = true
			western_door = true
			paper_door = true
			bamboo_door = true
			swamp_door = true
			glass_door = true
			barn_door = true
			mystic_door = true
			whispering_door = true
			bark_glass_door = true
			classic_door = true

		[entries.wood_type.mcwfences]
			highley_gate = true
			picket_fence = true
			stockade_fence = true
			wired_fence = true
			horse_fence = true
			pyramid_gate = true

		[entries.wood_type.mcwbridges]
			bridge_pier = true
			rope_bridge = true
			log_bridge_middle = true
			rope_bridge_stair = true
			log_bridge_stair = true
			rail_bridge = true

		[entries.wood_type.regions_unexplored]
			branch = true

		[entries.wood_type.mcwpaths]
			planks_path = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.mcwlights]
			tiki_torch = true
			soul_tiki_torch = true
			ceiling_fan_light = true

		[entries.wood_type.storagedrawers]
			full_drawers_2 = true
			full_drawers_4 = true
			full_drawers_1 = true
			half_drawers_1 = true
			half_drawers_4 = true
			half_drawers_2 = true
			trim = true

		[entries.wood_type.boatload]
			large_boat = true
			furnace_boat = true

		[entries.wood_type.create]
			window_pane = true
			window = true

		[entries.leaves_type.regions_unexplored]
			shrub = true

		[entries.leaves_type.mcwfences]
			hedge = true
